#!/bin/bash
set -ex

# A simple example of how to use the arbitrary process group to install a Neo4j instance.

if [ ! -d /mnt/rdafs/arbitrary/neo4j-binaries ]; then
	mkdir -p /mnt/rdafs/arbitrary/neo4j-binaries
fi

if [ ! -d /mnt/rdafs/arbitrary/jdk7-binaries ]; then
	mkdir -p /mnt/rdafs/arbitrary/jdk7-binaries
fi

if [ ! -f /mnt/rdafs/arbitrary/jdk7-binaries/jdk-7u60-linux-x64.tar.gz ]; then
	cd /mnt/rdafs/arbitrary/jdk7-binaries
	wget -O /mnt/rdafs/arbitrary/jdk7-binaries/jdk-7u60-linux-x64.tar.gz --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/7u60-b19/jdk-7u60-linux-x64.tar.gz
	tar -xzvf /mnt/rdafs/arbitrary/jdk7-binaries/jdk-7u60-linux-x64.tar.gz
	export JAVA_HOME=/mnt/rdafs/arbitrary/jdk7-binaries/jdk1.7.0_60
	export PATH=$JAVA_HOME/bin:$PATH
fi

if [ ! -d /mnt/rdafs/arbitrary/neo4j-data ]; then
	mkdir -p /mnt/rdafs/arbitrary/neo4j-data
fi

if [ ! -f /mnt/rdafs/arbitrary/neo4j-binaries/neo4j-community-2.1.2-unix.tar.gz ]; then
	cd /mnt/rdafs/arbitrary/neo4j-binaries

	wget -O /mnt/rdafs/arbitrary/neo4j-binaries/neo4j-community-2.1.2-unix.tar.gz "http://download.neo4j.org/artifact?edition=community&version=2.1.2&distribution=tarball&dlid=4559134&_ga=1.256044808.2001421697.1402776813"

	tar -xzvf ./neo4j-community-2.1.2-unix.tar.gz
	
	perl -i -pe 's:org.neo4j.server.database.location=data/graph.db:org.neo4j.server.database.location=/mnt/rdafs/arbitrary/neo4j-data/graph.db:g' /mnt/rdafs/arbitrary/neo4j-binaries/neo4j-community-2.1.2/conf/neo4j-server.properties
	
	perl -i -pe 's:org.neo4j.server.webadmin.rrdb.location=data/rrd:org.neo4j.server.webadmin.rrdb.location=/mnt/rdafs/arbitrary/neo4j-data/rrd:g' /mnt/rdafs/arbitrary/neo4j-binaries/neo4j-community-2.1.2/conf/neo4j-server.properties
fi