#!/bin/bash
set -e

# Unlink hadoop configs
update-alternatives --set hadoop-conf /etc/hadoop/conf.empty
update-alternatives --remove hadoop-conf ${deb.install.prefix}/cluster

# cleanup
rm -fv /usr/local/bin/datanode-watchdog.sh
rm -rfv ${deb.install.prefix}