# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "hashicorp/precise64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder "../../../../../", "/vagrant_data", id: "vagrant-root",
  mount_options: ["dmode=775,fmode=664"]

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
     vb.memory = "2048"
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end
	$script = <<SCRIPT
	
	apt-get -y update
	
	apt-get -y install wget curl tofrodos openjdk-6-jdk python-setuptools python-pip python-dev gcc sudo
	
	pip install ansible==1.8.3 boto pysphere 
	mkdir -m 0755 -p /etc/ansible 
	echo '' > /etc/ansible/hosts 
	
	wget -q -O ~/apache-maven-3.0.5-bin.tar.gz "http://mirror.cc.columbia.edu/pub/software/apache/maven/maven-3/3.0.5/binaries/apache-maven-3.0.5-bin.tar.gz"
	tar -C /usr/local -xzf ~/apache-maven-3.0.5-bin.tar.gz
	echo 'export PATH=$PATH:/usr/local/apache-maven-3.0.5/bin' > /etc/profile.d/maven.sh
	rm ~/apache-maven-3.0.5-bin.tar.gz
	chmod +x /etc/profile.d/maven.sh
	
	wget -q -O ~/apache-ant-1.9.5-bin.zip "http://download.nextag.com/apache//ant/binaries/apache-ant-1.9.5-bin.zip"
	cd /usr/local ; unzip ~/apache-ant-1.9.5-bin.zip 
	echo 'export PATH=$PATH:/usr/local/apache-ant-1.9.5/bin' > /etc/profile.d/ant.sh
	rm ~/apache-ant-1.9.5-bin.zip
	chmod +x /etc/profile.d/ant.sh
	

	echo 'Done provisioning vm.  Use it.'
SCRIPT
  
  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell",
     inline: $script   
end
