#!/bin/bash
set -e

# Run accumulo as a accumulo system user
adduser --system --group --home /var/lib/accumulo --gecos "Accumulo User" --shell /bin/bash accumulo  > /dev/null

cp -f ${deb.install.prefix}/cluster/* /usr/lib/accumulo-1.4.1/conf/.
chown -R accumulo:accumulo /usr/lib/accumulo-1.4.1 /mnt/rdafs/data/accumulo
chmod u+w /usr/lib/accumulo-1.4.1/conf/*
fromdos -f /usr/lib/accumulo-1.4.1/conf/*

# Move the modified start-server.sh script to the bin directory
cp -fv ${deb.install.prefix}/cluster/start-server.sh /usr/lib/accumulo-1.4.1/bin/.
chown accumulo:accumulo /usr/lib/accumulo-1.4.1/bin/start-server.sh ; chmod a+x /usr/lib/accumulo-1.4.1/bin/start-server.sh
rm -fv /usr/lib/accumulo-1.4.1/conf/start-server.sh

# Update the JAVA_HOME & HADOOP_HOME & ZOOKEEPER_HOME to their real locations   ($JAVA_HOME,/usr/lib/hadoop,/usr/lib/zookeeper)
perl -i -pe 's/&& export JAVA_HOME=\/path\/to\/java/&& export JAVA_HOME=\/usr\/lib\/jvm\/java-6-openjdk/g' /usr/lib/accumulo-1.4.1/conf/accumulo-env.sh
perl -i -pe 's/&& export HADOOP_HOME=\/path\/to\/hadoop/&& export HADOOP_HOME=\/usr\/lib\/hadoop/g' /usr/lib/accumulo-1.4.1/conf/accumulo-env.sh
perl -i -pe 's/&& export ZOOKEEPER_HOME=\/path\/to\/zookeeper/&& export ZOOKEEPER_HOME=\/usr\/lib\/zookeeper/g' /usr/lib/accumulo-1.4.1/conf/accumulo-env.sh

# Set the heap size to specific values (can't assume % of available due to other components on the same node)
AVAILABLE_MEMORY_IN_MB="$(free -m | grep Mem | awk '{print $2}')"
export RTWS_ACCUMULO_HEAPSIZE=6144

if [ -z $AVAILABLE_MEMORY_IN_MB ]; then
        echo "Unable to determine the amount of available memory, using defaults." | logger
else
        # If less than or equal4 GB, only allocate 1 GB
        if [ $AVAILABLE_MEMORY_IN_MB -le 4096 ]; then
            export RTWS_ACCUMULO_HEAPSIZE=1024
            
        # If less than or equal 7 GB, allocate 4 GB
        elif [ $AVAILABLE_MEMORY_IN_MB -le 8192 ]; then
            export RTWS_ACCUMULO_HEAPSIZE=4096
                
        # If less than or equal 12 GB, allocate 8 GB
        elif [ $AVAILABLE_MEMORY_IN_MB -le 12288 ]; then
            export RTWS_ACCUMULO_HEAPSIZE=8192
            
        # If more than 32 GB, only allocate 16 GB
        elif [ $AVAILABLE_MEMORY_IN_MB -ge 32768 ]; then                
            export RTWS_ACCUMULO_HEAPSIZE=16384
        fi
fi
perl -i -pe 's/RTWS_ACCUMULO_HEAPSIZE/$ENV{RTWS_ACCUMULO_HEAPSIZE}/g' /usr/lib/accumulo-1.4.1/conf/accumulo-env.sh

# Set the Zookeeper quorum
export CONFIGURED_QUORUM="$(grep RTWS_ZOOKEEPER_QUORUM_SERVERS /etc/rtwsrc | awk -F'=' '{print $2}')"
perl -i -pe 's/RTWS_ZOOKEEPER_QUORUM_SERVERS/$ENV{CONFIGURED_QUORUM}/g' /usr/lib/accumulo-1.4.1/conf/accumulo-site.xml

# Change default logging level to info 
perl -i -pe 's/DEBUG/INFO/g' /usr/lib/accumulo-1.4.1/conf/generic_logger.xml
perl -i -pe 's/DEBUG/INFO/g' /usr/lib/accumulo-1.4.1/conf/monitor_logger.xml

# Update the secret password
perl -i -pe 's/\<value\>secret\<\/value\>/\<value\>changeme\<\/value\>/g' /usr/lib/accumulo-1.4.1/conf/accumulo-site.xml

# Ensure the correct perms exist
chown -R accumulo:accumulo /usr/lib/accumulo-1.4.1
