#!/usr/bin/env python
"The XXstop python scripts behave like their bash counterparts, however there are a few differences.  For one, the first line of this script tells Linux"
"to invoke the python interpreter to execute the desired shutdown behavior as created by this script."
"Second, care must be taken to only import those python modules which are already installed on the custom process group."

# Main
if __name__ == '__main__':    
    print 'Your stop items go here.'