-- TODO: Change x.x.x to the tag version
INSERT INTO APPLICATION.SOFTWARE_RELEASES VALUES('1.0.3', 'The 1.0.3 software release version', '');

-- Change the x.x.x to the tag version and the ami ids if a new one was created
INSERT INTO APPLICATION.MACHINE_IMAGES VALUES('AWS', 'us-east-1', '1.0.3', 'ami-0cba3e65', 'ami-9a45c1f3');
INSERT INTO APPLICATION.MACHINE_IMAGES VALUES('AWS', 'us-west-1', '1.0.3', 'ami-0cba3e65', 'ami-9a45c1f3');
INSERT INTO APPLICATION.MACHINE_IMAGES VALUES('AWS', 'us-west-2', '1.0.3', 'ami-0cba3e65', 'ami-9a45c1f3');

-- Add additional process groups for S2i datasinks
INSERT INTO "APPLICATION"."PROCESS_GROUP_CONFIG" (PROCESS_GROUP_NAME,SECURITY_GROUP,INTERNAL_DOMAIN_NAME,MANAGEMENT_INTERFACES,PUBLIC_DOMAIN_NAME,DEFAULT_INSTANCE_TYPE,INSTANCE_STORAGE,FIXED_WEBAPPS,MANIFEST_FILENAME,INGEST_CONFIG_FILENAME,CONFIG_PERMISSIONS) VALUES ('hadoop.hbase.datanode.regionserver.v2','internal.default','dtanrgs-v2?.@build.domain@','','','m1.large','instance','','cloudera-datanode-regionserver-v2.ini','','{"default-num-volumes" : 2, "default-volume-size" : 50,  "config-volume-size" : true, "config-persistent-ip" : false, "config-instance-size" : false, "config-min-max" : true, "config-scaling" : true, "config-jms-persistence" : false }');
INSERT INTO "APPLICATION"."PROCESS_GROUP_CONFIG" (PROCESS_GROUP_NAME,SECURITY_GROUP,INTERNAL_DOMAIN_NAME,MANAGEMENT_INTERFACES,PUBLIC_DOMAIN_NAME,DEFAULT_INSTANCE_TYPE,INSTANCE_STORAGE,FIXED_WEBAPPS,MANIFEST_FILENAME,INGEST_CONFIG_FILENAME,CONFIG_PERMISSIONS) VALUES ('hadoop.hbase.namenode-master.v2','internal.default','namenode-v2.@build.domain@','','','m1.large','instance','','cloudera-master-v2.ini','','{"default-num-volumes" : 2, "default-volume-size" : 50,  "config-volume-size" : true, "config-persistent-ip" : false, "config-instance-size" : false, "config-min-max" : false, "config-scaling" : false, "config-jms-persistence" : false }');
INSERT INTO "APPLICATION"."PROCESS_GROUP_CONFIG" (PROCESS_GROUP_NAME,SECURITY_GROUP,INTERNAL_DOMAIN_NAME,MANAGEMENT_INTERFACES,PUBLIC_DOMAIN_NAME,DEFAULT_INSTANCE_TYPE,INSTANCE_STORAGE,FIXED_WEBAPPS,MANIFEST_FILENAME,INGEST_CONFIG_FILENAME,CONFIG_PERMISSIONS) VALUES ('hadoop.jobtracker.v2','internal.default','jobtracker-v2.@build.domain@','','','m1.large','instance','','cloudera-jobtracker-v2.ini','','{"default-num-volumes" : 0, "default-volume-size" : 0,  "config-volume-size" : false, "config-persistent-ip" : false, "config-instance-size" : false, "config-min-max" : false, "config-scaling" : false, "config-jms-persistence" : false }');
INSERT INTO "APPLICATION"."PROCESS_GROUP_CONFIG" (PROCESS_GROUP_NAME,SECURITY_GROUP,INTERNAL_DOMAIN_NAME,MANAGEMENT_INTERFACES,PUBLIC_DOMAIN_NAME,DEFAULT_INSTANCE_TYPE,INSTANCE_STORAGE,FIXED_WEBAPPS,MANIFEST_FILENAME,INGEST_CONFIG_FILENAME,CONFIG_PERMISSIONS) VALUES ('zookeeper.v2','internal.default','zookeeper-v2?.@build.domain@','','','m1.medium','instance','','cloudera-zookeeper-v2.ini','','{"default-num-volumes" : 0, "default-volume-size" : 0,  "config-volume-size" : false, "config-persistent-ip" : false, "config-instance-size" : false, "config-min-max" : true, "config-scaling" : false, "config-jms-persistence" : false }');
INSERT INTO "APPLICATION"."PROCESS_GROUP_CONFIG" (PROCESS_GROUP_NAME,SECURITY_GROUP,INTERNAL_DOMAIN_NAME,MANAGEMENT_INTERFACES,PUBLIC_DOMAIN_NAME,DEFAULT_INSTANCE_TYPE,INSTANCE_STORAGE,FIXED_WEBAPPS,MANIFEST_FILENAME,INGEST_CONFIG_FILENAME,CONFIG_PERMISSIONS) VALUES ('datasink.s2i','datasink.default','datasink-s2i-node?.@build.domain@','ingest.rtws.saic.com',null,'m1.large','instance',null,'datasink-s2i.ini','services.s2i.xml','{"default-num-volumes" : 0, "default-volume-size" : 0,  "config-volume-size" : true, "config-persistent-ip" : false, "config-instance-size" : true, "config-min-max" : true,  "config-scaling" : true,  "config-jms-persistence" : false }');
INSERT INTO "APPLICATION"."PROCESS_GROUP_CONFIG" (PROCESS_GROUP_NAME,SECURITY_GROUP,INTERNAL_DOMAIN_NAME,MANAGEMENT_INTERFACES,PUBLIC_DOMAIN_NAME,DEFAULT_INSTANCE_TYPE,INSTANCE_STORAGE,FIXED_WEBAPPS,MANIFEST_FILENAME,INGEST_CONFIG_FILENAME,CONFIG_PERMISSIONS) VALUES ('datasink.exts2i','datasink.default','datasink-s2i-node?.@build.domain@','ingest.rtws.saic.com',null,'m1.large','instance',null,'datasink-s2i-ext.ini','services.exts2i.xml','{"default-num-volumes" : 0, "default-volume-size" : 0,  "config-volume-size" : true, "config-persistent-ip" : false, "config-instance-size" : true, "config-min-max" : true,  "config-scaling" : true,  "config-jms-persistence" : false }');
INSERT INTO "APPLICATION"."DATASINK_CONFIG" (FQN,CAN_AUTOSCALE,USES_BLOCK_STORAGE,SCALE_UP_FACTOR,INGEST_CONFIG_FILENAME,PIPELINE_XML_FILENAME,PIPELINE_XML_TEMPLATE,PROCESS_GROUP_DEPENDENCIES) VALUES ('com.deleidos.rtws.ext.datasink.SaicScale2InsightDataSink','Y','N',1,'','','','zookeeper.v2, hadoop.hbase.namenode-master.v2, hadoop.jobtracker.v2, hadoop.hbase.datanode.regionserver.v2, datasink.s2i');
INSERT INTO "APPLICATION"."DATASINK_CONFIG" (FQN,CAN_AUTOSCALE,USES_BLOCK_STORAGE,SCALE_UP_FACTOR,INGEST_CONFIG_FILENAME,PIPELINE_XML_FILENAME,PIPELINE_XML_TEMPLATE,PROCESS_GROUP_DEPENDENCIES) VALUES ('com.deleidos.rtws.ext.datasink.ExternalSaicScale2InsightDataSink','Y','N',1,'','','','datasink.exts2i');

-- Add additional process groups for Accumulo cluster & datasink
INSERT INTO "APPLICATION"."PROCESS_GROUP_CONFIG" (PROCESS_GROUP_NAME,SECURITY_GROUP,INTERNAL_DOMAIN_NAME,MANAGEMENT_INTERFACES,PUBLIC_DOMAIN_NAME,DEFAULT_INSTANCE_TYPE,INSTANCE_STORAGE,FIXED_WEBAPPS,MANIFEST_FILENAME,INGEST_CONFIG_FILENAME,CONFIG_PERMISSIONS) VALUES ('hadoop.accumulo.datanode.tabletserver','internal.default','dtatblt?.@build.domain@','','','m1.large','instance','','accumulo-datanode-tabletserver.ini','','{"default-num-volumes" : 2, "default-volume-size" : 50,  "config-volume-size" : true, "config-persistent-ip" : false, "config-instance-size" : false, "config-min-max" : true, "config-scaling" : true, "config-jms-persistence" : false }');
INSERT INTO "APPLICATION"."PROCESS_GROUP_CONFIG" (PROCESS_GROUP_NAME,SECURITY_GROUP,INTERNAL_DOMAIN_NAME,MANAGEMENT_INTERFACES,PUBLIC_DOMAIN_NAME,DEFAULT_INSTANCE_TYPE,INSTANCE_STORAGE,FIXED_WEBAPPS,MANIFEST_FILENAME,INGEST_CONFIG_FILENAME,CONFIG_PERMISSIONS) VALUES ('hadoop.accumulo.namenode-master','internal.default','namenode.@build.domain@','','','m1.large','instance','','accumulo-master.ini','','{"default-num-volumes" : 2, "default-volume-size" : 50,  "config-volume-size" : true, "config-persistent-ip" : false, "config-instance-size" : false, "config-min-max" : false, "config-scaling" : false, "config-jms-persistence" : false }');
INSERT INTO "APPLICATION"."PROCESS_GROUP_CONFIG" (PROCESS_GROUP_NAME,SECURITY_GROUP,INTERNAL_DOMAIN_NAME,MANAGEMENT_INTERFACES,PUBLIC_DOMAIN_NAME,DEFAULT_INSTANCE_TYPE,INSTANCE_STORAGE,FIXED_WEBAPPS,MANIFEST_FILENAME,INGEST_CONFIG_FILENAME,CONFIG_PERMISSIONS) VALUES ('datasink.accumulo','datasink.default','datasink-accumulo-node?.@build.domain@','ingest.rtws.saic.com',null,'m1.large','instance',null,'accumulo.ini','services.accumulo.xml','{"default-num-volumes" : 0, "default-volume-size" : 0,  "config-volume-size" : true, "config-persistent-ip" : false, "config-instance-size" : true, "config-min-max" : true,  "config-scaling" : true,  "config-jms-persistence" : false }');
INSERT INTO "APPLICATION"."DATASINK_CONFIG" (FQN,CAN_AUTOSCALE,USES_BLOCK_STORAGE,SCALE_UP_FACTOR,INGEST_CONFIG_FILENAME,PIPELINE_XML_FILENAME,PIPELINE_XML_TEMPLATE,PROCESS_GROUP_DEPENDENCIES) VALUES ('gov.navair.datasink.AccumuloDataSink','Y','N',1,'','','','zookeeper, hadoop.accumulo.namenode-master, hadoop.jobtracker, hadoop.accumulo.datanode.tabletserver, datasink.accumulo');

-- Add apt-mirror process group
INSERT INTO APPLICATION.PROCESS_GROUP_CONFIG VALUES ('apt.mirror','internal.default','mirror.@build.domain@','','','m1.medium','instance','','apt-mirror.ini','','{"default-num-volumes" : 1, "default-volume-size" : 15,  "config-volume-size" : true, "config-persistent-ip" : true, "config-instance-size" : false, "config-min-max" : false,  "config-scaling" : false,  "config-jms-persistence" : false }');
INSERT INTO APPLICATION.WEBAPPS_CONFIG (FQN,TYPE,DESCRIPTION,WEBAPPS_DEPENDENCIES,DATASINK_DEPENDENCIES) VALUES ('processgroup:apt.mirror','server','Provides an apt-mirror for software installation of dependent components.','','');

CREATE TABLE IF NOT EXISTS APPLICATION.REGISTRATION(
	EMAIL_ADDRESS 			VARCHAR(255),
	REGISTRATION_UUID		VARCHAR(255),
	EXPIRATION_TIMESTAMP	TIMESTAMP,
	EMAIL_TIMESTAMP			TIMESTAMP,
	
	CONSTRAINT EMAIL_ADDRESS_NAMING UNIQUE (EMAIL_ADDRESS) 
);

ALTER TABLE APPLICATION.IAAS_ACCOUNTS ADD LICENSE_EXPIRATION_TIMESTAMP TIMESTAMP DEFAULT NULL;

-- Commit
commit;
