ALTER TABLE APPLICATION.PROCESS_GROUP_CONFIG ADD SERVICE_ENABLED BOOLEAN;

UPDATE APPLICATION.PROCESS_GROUP_CONFIG SET SERVICE_ENABLED=TRUE WHERE PROCESS_GROUP_NAME='jms.external' or PROCESS_GROUP_NAME='jms.internal' 
or PROCESS_GROUP_NAME='apache.http';

UPDATE APPLICATION.DATASINK_CONFIG SET PROCESS_GROUP_DEPENDENCIES='elasticsearch,kibana,cas.auth,datasink.elasticsearch' WHERE FQN='com.deleidos.datasink.elasticsearch.ElasticSearchDataSink1_4'

UPDATE APPLICATION.PROCESS_GROUP_CONFIG SET CONTAINER_PORT_EXPOSE_HOST='443:8443' WHERE PROCESS_GROUP_NAME='cas.auth'

CREATE TABLE "APPLICATION"."SYSTEM_CHAINS"
(
   NAME varchar(512) NOT NULL,
   ACCOUNT_ID decimal(65535,32767) NOT NULL,
   DOMAIN varchar(512) NOT NULL,
   REGION varchar(64),
   CFG_VERSION varchar(64) NOT NULL,
   POSITION decimal(65535,32767) NOT NULL
)
;
ALTER TABLE "APPLICATION"."SYSTEM_CHAINS"
ADD CONSTRAINT CONSTRAINT_BC
FOREIGN KEY (ACCOUNT_ID)
REFERENCES "APPLICATION"."IAAS_ACCOUNTS"(ACCOUNT_ID)
;
CREATE INDEX CONSTRAINT_INDEX_B ON "APPLICATION"."SYSTEM_CHAINS"(ACCOUNT_ID)
;
