ALTER TABLE APPLICATION.ACCOUNT_SYSTEMS ADD COLUMN IF NOT EXISTS MASTER_REGION VARCHAR(64) NOT NULL DEFAULT 'us-east-1';

ALTER TABLE APPLICATION.IAAS_ACCOUNTS ADD COLUMN IF NOT EXISTS EULA_ACCEPTED_TIMESTAMP TIMESTAMP;

DELETE FROM APPLICATION.DATASINK_CONFIG where FQN = 'com.deleidos.rtws.ext.datasink.GotoMetricsDataSink';
DELETE FROM APPLICATION.PROCESS_GROUP_CONFIG where PROCESS_GROUP_NAME like '%gotometrics%';

DELETE FROM APPLICATION.DATASINK_CONFIG where FQN = 'com.deleidos.rtws.ext.datasink.DynamoDbDataSink';
DELETE FROM APPLICATION.PROCESS_GROUP_CONFIG where PROCESS_GROUP_NAME = 'datasink.dynamo';

CREATE TABLE IF NOT EXISTS APPLICATION.GATEWAY_ACCOUNTS(
	ACCOUNT_ID				NUMBER			NOT NULL,
	INSTANCE_ID				VARCHAR2(64),
	PUBLIC_DNS				VARCHAR2(255),
	REGION					VARCHAR2(64),
	REGISTRATION_TIMESTAMP	TIMESTAMP,
	
	CONSTRAINT ACCOUNT_ID_FK FOREIGN KEY(ACCOUNT_ID) REFERENCES APPLICATION.IAAS_ACCOUNTS(ACCOUNT_ID),
	CONSTRAINT GA_NAMING UNIQUE (ACCOUNT_ID, REGION) 
);
GRANT ALL ON APPLICATION.GATEWAY_ACCOUNTS TO APPUSER;

UPDATE APPLICATION.WEBAPPS_CONFIG
SET DATASINK_DEPENDENCIES='com.deleidos.rtws.ext.datasink.SaicAlertingDataSink'
WHERE FQN='com.deleidos.rtws.alertviz' OR FQN='com.deleidos.rtws.webapp.alertsapi';

INSERT INTO APPLICATION.SOFTWARE_RELEASES VALUE('0.9.8', 'The beta software release version', '');

INSERT INTO APPLICATION.MACHINE_IMAGES VALUES('AWS', 'us-east-1', '0.9.8', 'ami-b38d22da', 'ami-118d2278', 'ami-b38d22da', 'ami-118d2278');
INSERT INTO APPLICATION.MACHINE_IMAGES VALUES('AWS', 'us-west-1', '0.9.8', 'ami-b38d22da', 'ami-118d2278', 'ami-b38d22da', 'ami-118d2278');
INSERT INTO APPLICATION.MACHINE_IMAGES VALUES('AWS', 'us-west-2', '0.9.8', 'ami-b38d22da', 'ami-118d2278', 'ami-b38d22da', 'ami-118d2278');
