CREATE TABLE IF NOT EXISTS "APPLICATION"."MACHINE_IMAGES"
(
   IAAS_SERVICE_NAME varchar(64),
   IAAS_REGION varchar(64),
   SW_VERSION_ID varchar(64),
   MI_64BIT_INSTANCE varchar(32),
   TENANT_ID varchar(255) DEFAULT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS MI_NAMING_INDEX_5 ON "APPLICATION"."MACHINE_IMAGES"
(
  IAAS_SERVICE_NAME,
  IAAS_REGION,
  SW_VERSION_ID,
  TENANT_ID
);

INSERT INTO "APPLICATION"."MACHINE_IMAGES" (IAAS_SERVICE_NAME,IAAS_REGION,SW_VERSION_ID,MI_64BIT_INSTANCE,TENANT_ID) VALUES ('AWS','us-east-1','rtws-nightly.2013-04-18_1606','ami-805431e9','aws-dev');
INSERT INTO "APPLICATION"."MACHINE_IMAGES" (IAAS_SERVICE_NAME,IAAS_REGION,SW_VERSION_ID,MI_64BIT_INSTANCE,TENANT_ID) VALUES ('AWS','us-east-1','rtws-nightly.2013-04-18_1606','ami-805431e9','mkt-dev');
INSERT INTO "APPLICATION"."MACHINE_IMAGES" (IAAS_SERVICE_NAME,IAAS_REGION,SW_VERSION_ID,MI_64BIT_INSTANCE,TENANT_ID) VALUES ('AWS','us-east-1','rtws-nightly.2013-04-18_1606','ami-805431e9','tms-dev');
INSERT INTO "APPLICATION"."MACHINE_IMAGES" (IAAS_SERVICE_NAME,IAAS_REGION,SW_VERSION_ID,MI_64BIT_INSTANCE,TENANT_ID) VALUES ('AWS','us-east-1','rtws-nightly.2013-04-18_1606','ami-805431e9','tms-test');