CREATE TABLE IF NOT EXISTS "APPLICATION"."INSTANCE_TYPES"
(
   INSTANCE_TYPE varchar(32) PRIMARY KEY NOT NULL,
   NUM_BITS decimal(65535,32767) NOT NULL,
   NUM_CORES decimal(65535,32767) NOT NULL,
   MEMORY_MB decimal(65535,32767) NOT NULL
)
;
CREATE UNIQUE INDEX IF NOT EXISTS PRIMARY_KEY_B ON "APPLICATION"."INSTANCE_TYPES"(INSTANCE_TYPE)
;


INSERT INTO "APPLICATION"."INSTANCE_TYPES" (INSTANCE_TYPE,NUM_BITS,NUM_CORES,MEMORY_MB) VALUES ('m1.large',64,2,7680);
INSERT INTO "APPLICATION"."INSTANCE_TYPES" (INSTANCE_TYPE,NUM_BITS,NUM_CORES,MEMORY_MB) VALUES ('m1.medium',64,2,3840);
INSERT INTO "APPLICATION"."INSTANCE_TYPES" (INSTANCE_TYPE,NUM_BITS,NUM_CORES,MEMORY_MB) VALUES ('m1.small',64,1,1700);
INSERT INTO "APPLICATION"."INSTANCE_TYPES" (INSTANCE_TYPE,NUM_BITS,NUM_CORES,MEMORY_MB) VALUES ('m1.xlarge',64,4,15000);
INSERT INTO "APPLICATION"."INSTANCE_TYPES" (INSTANCE_TYPE,NUM_BITS,NUM_CORES,MEMORY_MB) VALUES ('m2.2xlarge',64,4,34200);
INSERT INTO "APPLICATION"."INSTANCE_TYPES" (INSTANCE_TYPE,NUM_BITS,NUM_CORES,MEMORY_MB) VALUES ('m2.4xlarge',64,8,68400);
INSERT INTO "APPLICATION"."INSTANCE_TYPES" (INSTANCE_TYPE,NUM_BITS,NUM_CORES,MEMORY_MB) VALUES ('m2.xlarge',64,2,17100);
INSERT INTO "APPLICATION"."INSTANCE_TYPES" (INSTANCE_TYPE,NUM_BITS,NUM_CORES,MEMORY_MB) VALUES ('t1.micro',64,1,613);
