CREATE TABLE IF NOT EXISTS "APPLICATION"."NAMED_FILTER"
(
   KEY decimal(65535,32767) PRIMARY KEY NOT NULL,
   NAME varchar(25) NOT NULL,
   MODEL varchar(100) NOT NULL,
   DEFINITION varchar(4000) NOT NULL,
   EMAIL_SUBJECT varchar(100),
   EMAIL_MESSAGE varchar(4000)
)
;
CREATE UNIQUE INDEX IF NOT EXISTS PRIMARY_KEY_4 ON "APPLICATION"."NAMED_FILTER"(KEY)
;
CREATE UNIQUE INDEX IF NOT EXISTS NAMED_FILTER_UNIQUE ON "APPLICATION"."NAMED_FILTER"
(
  NAME,
  MODEL
)
;
CREATE TABLE IF NOT EXISTS "APPLICATION"."NAMED_FILTER_USERS"
(
   KEY decimal(65535,32767) PRIMARY KEY NOT NULL,
   USERNAME varchar(25) NOT NULL,
   PASSWORD varchar(125) NOT NULL,
   EMAIL_LIST varchar(4000)
)
;
CREATE UNIQUE INDEX IF NOT EXISTS PRIMARY_KEY_46 ON "APPLICATION"."NAMED_FILTER_USERS"(KEY)
;
CREATE UNIQUE INDEX IF NOT EXISTS NAMED_FILTER_USERS_UNIQUE ON "APPLICATION"."NAMED_FILTER_USERS"(USERNAME)
;
CREATE TABLE IF NOT EXISTS "APPLICATION"."NAMED_FILTER_WATCHLIST"
(
   USER_KEY decimal(65535,32767) NOT NULL,
   FILTER_KEY decimal(65535,32767) NOT NULL,
   COLOR decimal(65535,32767),
   EMAIL varchar(1),
   CONSTRAINT NAMED_FILTER_WATCHLIST_PK PRIMARY KEY (USER_KEY,FILTER_KEY)
)
;
CREATE UNIQUE INDEX IF NOT EXISTS PRIMARY_KEY_F ON "APPLICATION"."NAMED_FILTER_WATCHLIST"
(
  USER_KEY,
  FILTER_KEY
)
;



INSERT INTO "APPLICATION"."NAMED_FILTER_USERS" (KEY,USERNAME,PASSWORD,EMAIL_LIST) VALUES (1,'futo','redacted',null);
INSERT INTO "APPLICATION"."NAMED_FILTER_USERS" (KEY,USERNAME,PASSWORD,EMAIL_LIST) VALUES (2,'moserm','redacted','moserm@saic.com,michael.w.moser@saic.com');
INSERT INTO "APPLICATION"."NAMED_FILTER_USERS" (KEY,USERNAME,PASSWORD,EMAIL_LIST) VALUES (3,'farrellj','redacted',null);
INSERT INTO "APPLICATION"."NAMED_FILTER_USERS" (KEY,USERNAME,PASSWORD,EMAIL_LIST) VALUES (21,'tragesere','redacted',null);
INSERT INTO "APPLICATION"."NAMED_FILTER_USERS" (KEY,USERNAME,PASSWORD,EMAIL_LIST) VALUES (22,'floydac','redacted',null);
INSERT INTO "APPLICATION"."NAMED_FILTER_USERS" (KEY,USERNAME,PASSWORD,EMAIL_LIST) VALUES (23,'vahlbergm','redacted',null);
INSERT INTO "APPLICATION"."NAMED_FILTER_USERS" (KEY,USERNAME,PASSWORD,EMAIL_LIST) VALUES (24,'cannaliatot','redacted',null);
INSERT INTO "APPLICATION"."NAMED_FILTER_USERS" (KEY,USERNAME,PASSWORD,EMAIL_LIST) VALUES (25,'rainerr','redacted',null);
INSERT INTO "APPLICATION"."NAMED_FILTER_USERS" (KEY,USERNAME,PASSWORD,EMAIL_LIST) VALUES (26,'stocksdalet','redacted',null);
INSERT INTO "APPLICATION"."NAMED_FILTER_USERS" (KEY,USERNAME,PASSWORD,EMAIL_LIST) VALUES (27,'jaffeee','redacted',null);
INSERT INTO "APPLICATION"."NAMED_FILTER_USERS" (KEY,USERNAME,PASSWORD,EMAIL_LIST) VALUES (41,'guest','redacted',null);
INSERT INTO "APPLICATION"."NAMED_FILTER_USERS" (KEY,USERNAME,PASSWORD,EMAIL_LIST) VALUES (50,'wichtendahlw','redacted',null);
INSERT INTO "APPLICATION"."NAMED_FILTER_USERS" (KEY,USERNAME,PASSWORD,EMAIL_LIST) VALUES (51,'morrisonjb','redacted','morrisonjb@saic.com');


INSERT INTO "APPLICATION"."NAMED_FILTER" (KEY,NAME,MODEL,DEFINITION,EMAIL_SUBJECT,EMAIL_MESSAGE) VALUES (1,'Near Baltimore','transportation','{"geoList":[{"geoGrid":{"name":"IN (''18SUJ5437L001'', ''18SUJ5438L001'', ''18SUJ5439L001'', ''18SUJ5537L001'', ''18SUJ5538L001'', ''18SUJ5539L001'', ''18SUJ5637L001'', ''18SUJ5638L001'', ''18SUJ5639L001'')"}}]}',null,null);


