CREATE TABLE IF NOT EXISTS APPLICATION.IAAS_ACCOUNTS(
    ACCOUNT_ID						NUMBER			NOT NULL,
    ACCOUNT_NAME					VARCHAR2(255)	NOT NULL,
    DESCRIPTION						VARCHAR2(512)	NOT NULL,
    IAAS_SERVICE_NAME   			VARCHAR2(64)	NOT NULL,
    IAAS_SERVICE_NUMBER 			VARCHAR2(255),
    KEYPAIR_NAME					VARCHAR2(255)	NOT NULL,
    ANCHOR_INSTANCE_ID				VARCHAR2(255),
    AWS_ACCOUNT_EMAIL				VARCHAR2(64)	NOT NULL,
    DOMAIN_NAME_SUFFIX				VARCHAR2(255)	NOT NULL,
    EULA_ACCEPTED_TIMESTAMP			TIMESTAMP,
    LICENSE_EXPIRATION_TIMESTAMP	TIMESTAMP,

    CONSTRAINT ACCOUNT_ID_PK PRIMARY KEY (ACCOUNT_ID)
);

insert into application.IAAS_ACCOUNTS (ACCOUNT_ID,ACCOUNT_NAME,DESCRIPTION,IAAS_SERVICE_NAME,IAAS_SERVICE_NUMBER,KEYPAIR_NAME,AWS_ACCOUNT_EMAIL,DOMAIN_NAME_SUFFIX) 
						values  (8888,      'test',      'test',     'test',           'test',             'test',      'test@test.com',  'test.mydomain');