CREATE TABLE IF NOT EXISTS APPLICATION.DATASINK_CONFIG(
	FQN							VARCHAR2(512)	NOT NULL PRIMARY KEY,
	CAN_AUTOSCALE				CHAR(1)			NOT NULL,
	USES_BLOCK_STORAGE          CHAR(1)         NOT NULL,
	SCALE_UP_FACTOR             NUMBER          NOT NULL,
	PROCESS_GROUP_DEPENDENCIES	VARCHAR2(4000),
	NUM_THREADS					NUMBER 			NOT NULL DEFAULT 2
);

