CREATE TABLE IF NOT EXISTS APPLICATION.GATEWAY_ACCOUNTS(
	ACCOUNT_ID				NUMBER			NOT NULL,
	INSTANCE_ID				VARCHAR2(64),
	PUBLIC_DNS				VARCHAR2(255),
	REGION					VARCHAR2(64),
	REGISTRATION_TIMESTAMP	TIMESTAMP,
	AZONE					VARCHAR2(64),
	CONSTRAINT ACCOUNT_ID_FK FOREIGN KEY(ACCOUNT_ID) REFERENCES APPLICATION.IAAS_ACCOUNTS(ACCOUNT_ID),
	CONSTRAINT GA_NAMING UNIQUE (ACCOUNT_ID, REGION) 
);

insert into application.GATEWAY_ACCOUNTS (ACCOUNT_ID,REGION)
						values      (8888, 'us-east-1');