CREATE SEQUENCE if not exists PUBLIC.IAAS_ACCOUNT_ID_SEQ START WITH 3;
CREATE SEQUENCE if not exists PUBLIC.TENANT_RDBMS_CONNECTION_ID_SEQ START WITH 1;
CREATE SEQUENCE if not exists PUBLIC.DIM_TABLE_ID_SEQ START WITH 1;
CREATE SEQUENCE if not exists PUBLIC.DIM_COLUMN_ID_SEQ START WITH 1;
