CREATE TABLE IF NOT EXISTS "APPLICATION"."TENANT_ACCOUNT_ACCESS"
(
   TENANT_ID varchar(255) NOT NULL,
   ACCOUNT_ID decimal(65535,32767) NOT NULL
)
;
CREATE UNIQUE INDEX IF NOT EXISTS TENANT_ACCESS_UNIQUE_INDEX_4 ON "APPLICATION"."TENANT_ACCOUNT_ACCESS"(TENANT_ID)
;


INSERT INTO "APPLICATION"."TENANT_ACCOUNT_ACCESS" (TENANT_ID,ACCOUNT_ID) VALUES ('admin',3);
INSERT INTO "APPLICATION"."TENANT_ACCOUNT_ACCESS" (TENANT_ID,ACCOUNT_ID) VALUES ('aws-dev',1);
INSERT INTO "APPLICATION"."TENANT_ACCOUNT_ACCESS" (TENANT_ID,ACCOUNT_ID) VALUES ('aws-dev-test',1);
INSERT INTO "APPLICATION"."TENANT_ACCOUNT_ACCESS" (TENANT_ID,ACCOUNT_ID) VALUES ('bullockja',1);
INSERT INTO "APPLICATION"."TENANT_ACCOUNT_ACCESS" (TENANT_ID,ACCOUNT_ID) VALUES ('cv-dev',391);
INSERT INTO "APPLICATION"."TENANT_ACCOUNT_ACCESS" (TENANT_ID,ACCOUNT_ID) VALUES ('cv-dot',390);
INSERT INTO "APPLICATION"."TENANT_ACCOUNT_ACCESS" (TENANT_ID,ACCOUNT_ID) VALUES ('dev-test-2',461);
INSERT INTO "APPLICATION"."TENANT_ACCOUNT_ACCESS" (TENANT_ID,ACCOUNT_ID) VALUES ('futo',1);
INSERT INTO "APPLICATION"."TENANT_ACCOUNT_ACCESS" (TENANT_ID,ACCOUNT_ID) VALUES ('loomisn',1);
INSERT INTO "APPLICATION"."TENANT_ACCOUNT_ACCESS" (TENANT_ID,ACCOUNT_ID) VALUES ('mkt-dev',71);
INSERT INTO "APPLICATION"."TENANT_ACCOUNT_ACCESS" (TENANT_ID,ACCOUNT_ID) VALUES ('rockinsonm',1);
INSERT INTO "APPLICATION"."TENANT_ACCOUNT_ACCESS" (TENANT_ID,ACCOUNT_ID) VALUES ('tms',3);
