#!/bin/bash
set -e

source /etc/rtwsrc

# Apply HBase config
mkdir /etc/hbase/conf/.bkup ; mv -f /etc/hbase/conf/* /etc/hbase/conf/.bkup
ln -sf ${deb.install.prefix}/cluster/* /etc/hbase/conf/.
chown -h root:root /etc/hbase/conf/*

if [ -f ${deb.install.prefix}/phoenix/phoenix-2.2.2.jar ]; then
   if [ ! -z "$(echo $RTWS_PROCESS_GROUP | grep -w datanode)" ]; then
      cp ${deb.install.prefix}/phoenix/phoenix-2.2.2.jar /usr/lib/hbase/lib/.
   fi
fi

# Apply fix for init.d script's incorrect return code on status calls
fromdos -f ${deb.install.prefix}/init.d/hbase-regionserver
cp -f ${deb.install.prefix}/init.d/hbase-regionserver /etc/init.d/.

# Set the heap size to specific values (can't assume % of available due to other components on the same node)
AVAILABLE_MEMORY_IN_MB="$(free -m | grep Mem | awk '{print $2}')"
export RTWS_HBASE_HEAPSIZE=6144

if [ -z $AVAILABLE_MEMORY_IN_MB ]; then
        echo "Unable to determine the amount of available memory, using defaults." | logger
else
        # If less than or equal4 GB, only allocate 1 GB
        if [ $AVAILABLE_MEMORY_IN_MB -le 4096 ]; then
            export RTWS_HBASE_HEAPSIZE=1024
                
        # If less than or equal 7 GB, allocate 6 GB  (Assumes swap has been allocated)
        elif [ $AVAILABLE_MEMORY_IN_MB -le 6144 ]; then
            export RTWS_HBASE_HEAPSIZE=6144
            
        # If more than 32 GB, only allocate 16 GB
        elif [ $AVAILABLE_MEMORY_IN_MB -ge 32768 ]; then                
            export RTWS_HBASE_HEAPSIZE=16384
        fi
fi
perl -i -pe 's/export HBASE_HEAPSIZE=RTWS_HBASE_HEAPSIZE/export HBASE_HEAPSIZE=$ENV{RTWS_HBASE_HEAPSIZE}/g' /etc/hbase/conf/hbase-env.sh

# Detect correct interface to associate with HBase's wacky dns resolution algorithm
export IP="$(nslookup $RTWS_FQDN |grep Address |tail -1 | cut -d":" -f2 | tr -d '[:space:]')"

# TODO Revisit this simple logic for detecting the active interface
export R_RTWS_INTERFACE="$(ifconfig | head -2 | awk '{print $1}' | head -1)"
perl -i -pe "s/RTWS_INTERFACE/$R_RTWS_INTERFACE/g" /etc/hbase/conf/hbase-site.xml
