CREATE TABLE IF NOT EXISTS "DIMENSIONS"."SHIPMENT_INFO"
(
   SI_SHIPMENTKEY decimal(65535,32767),
   SI_PRIORITY varchar(15) NOT NULL,
   SI_INSTRUCTIONS varchar(25) NOT NULL,
   SI_MODE varchar(10) NOT NULL
)
;
CREATE UNIQUE INDEX IF NOT EXISTS SHIPMENT_INFO_NK_INDEX_9 ON "DIMENSIONS"."SHIPMENT_INFO"
(
  SI_PRIORITY,
  SI_INSTRUCTIONS,
  SI_MODE
)
;


INSERT INTO "DIMENSIONS"."SHIPMENT_INFO" (SI_SHIPMENTKEY,SI_PRIORITY,SI_INSTRUCTIONS,SI_MODE) VALUES (52981,'0','TAKE BACK RETURN','REG AIR');
INSERT INTO "DIMENSIONS"."SHIPMENT_INFO" (SI_SHIPMENTKEY,SI_PRIORITY,SI_INSTRUCTIONS,SI_MODE) VALUES (52982,'0','NONE','REG AIR');
INSERT INTO "DIMENSIONS"."SHIPMENT_INFO" (SI_SHIPMENTKEY,SI_PRIORITY,SI_INSTRUCTIONS,SI_MODE) VALUES (52983,'0','NONE','FOB');
INSERT INTO "DIMENSIONS"."SHIPMENT_INFO" (SI_SHIPMENTKEY,SI_PRIORITY,SI_INSTRUCTIONS,SI_MODE) VALUES (52984,'0','NONE','MAIL');
INSERT INTO "DIMENSIONS"."SHIPMENT_INFO" (SI_SHIPMENTKEY,SI_PRIORITY,SI_INSTRUCTIONS,SI_MODE) VALUES (52985,'0','NONE','AIR');
INSERT INTO "DIMENSIONS"."SHIPMENT_INFO" (SI_SHIPMENTKEY,SI_PRIORITY,SI_INSTRUCTIONS,SI_MODE) VALUES (52986,'0','TAKE BACK RETURN','TRUCK');
INSERT INTO "DIMENSIONS"."SHIPMENT_INFO" (SI_SHIPMENTKEY,SI_PRIORITY,SI_INSTRUCTIONS,SI_MODE) VALUES (52987,'0','COLLECT COD','FOB');
INSERT INTO "DIMENSIONS"."SHIPMENT_INFO" (SI_SHIPMENTKEY,SI_PRIORITY,SI_INSTRUCTIONS,SI_MODE) VALUES (52988,'0','TAKE BACK RETURN','SHIP');
INSERT INTO "DIMENSIONS"."SHIPMENT_INFO" (SI_SHIPMENTKEY,SI_PRIORITY,SI_INSTRUCTIONS,SI_MODE) VALUES (52989,'0','NONE','SHIP');
INSERT INTO "DIMENSIONS"."SHIPMENT_INFO" (SI_SHIPMENTKEY,SI_PRIORITY,SI_INSTRUCTIONS,SI_MODE) VALUES (52990,'0','DELIVER IN PERSON','MAIL');
INSERT INTO "DIMENSIONS"."SHIPMENT_INFO" (SI_SHIPMENTKEY,SI_PRIORITY,SI_INSTRUCTIONS,SI_MODE) VALUES (52991,'0','DELIVER IN PERSON','SHIP');
INSERT INTO "DIMENSIONS"."SHIPMENT_INFO" (SI_SHIPMENTKEY,SI_PRIORITY,SI_INSTRUCTIONS,SI_MODE) VALUES (52992,'0','TAKE BACK RETURN','AIR');
INSERT INTO "DIMENSIONS"."SHIPMENT_INFO" (SI_SHIPMENTKEY,SI_PRIORITY,SI_INSTRUCTIONS,SI_MODE) VALUES (52993,'0','NONE','RAIL');
INSERT INTO "DIMENSIONS"."SHIPMENT_INFO" (SI_SHIPMENTKEY,SI_PRIORITY,SI_INSTRUCTIONS,SI_MODE) VALUES (52994,'0','TAKE BACK RETURN','RAIL');
INSERT INTO "DIMENSIONS"."SHIPMENT_INFO" (SI_SHIPMENTKEY,SI_PRIORITY,SI_INSTRUCTIONS,SI_MODE) VALUES (52995,'0','DELIVER IN PERSON','RAIL');
INSERT INTO "DIMENSIONS"."SHIPMENT_INFO" (SI_SHIPMENTKEY,SI_PRIORITY,SI_INSTRUCTIONS,SI_MODE) VALUES (52996,'0','COLLECT COD','MAIL');
INSERT INTO "DIMENSIONS"."SHIPMENT_INFO" (SI_SHIPMENTKEY,SI_PRIORITY,SI_INSTRUCTIONS,SI_MODE) VALUES (52997,'0','DELIVER IN PERSON','TRUCK');
INSERT INTO "DIMENSIONS"."SHIPMENT_INFO" (SI_SHIPMENTKEY,SI_PRIORITY,SI_INSTRUCTIONS,SI_MODE) VALUES (52998,'0','COLLECT COD','TRUCK');
INSERT INTO "DIMENSIONS"."SHIPMENT_INFO" (SI_SHIPMENTKEY,SI_PRIORITY,SI_INSTRUCTIONS,SI_MODE) VALUES (52999,'0','COLLECT COD','REG AIR');
INSERT INTO "DIMENSIONS"."SHIPMENT_INFO" (SI_SHIPMENTKEY,SI_PRIORITY,SI_INSTRUCTIONS,SI_MODE) VALUES (53000,'0','COLLECT COD','SHIP');
INSERT INTO "DIMENSIONS"."SHIPMENT_INFO" (SI_SHIPMENTKEY,SI_PRIORITY,SI_INSTRUCTIONS,SI_MODE) VALUES (53001,'0','COLLECT COD','AIR');
INSERT INTO "DIMENSIONS"."SHIPMENT_INFO" (SI_SHIPMENTKEY,SI_PRIORITY,SI_INSTRUCTIONS,SI_MODE) VALUES (53002,'0','TAKE BACK RETURN','FOB');
INSERT INTO "DIMENSIONS"."SHIPMENT_INFO" (SI_SHIPMENTKEY,SI_PRIORITY,SI_INSTRUCTIONS,SI_MODE) VALUES (53003,'0','COLLECT COD','RAIL');
INSERT INTO "DIMENSIONS"."SHIPMENT_INFO" (SI_SHIPMENTKEY,SI_PRIORITY,SI_INSTRUCTIONS,SI_MODE) VALUES (53004,'0','TAKE BACK RETURN','MAIL');
INSERT INTO "DIMENSIONS"."SHIPMENT_INFO" (SI_SHIPMENTKEY,SI_PRIORITY,SI_INSTRUCTIONS,SI_MODE) VALUES (53005,'0','DELIVER IN PERSON','REG AIR');
INSERT INTO "DIMENSIONS"."SHIPMENT_INFO" (SI_SHIPMENTKEY,SI_PRIORITY,SI_INSTRUCTIONS,SI_MODE) VALUES (53006,'0','NONE','TRUCK');
INSERT INTO "DIMENSIONS"."SHIPMENT_INFO" (SI_SHIPMENTKEY,SI_PRIORITY,SI_INSTRUCTIONS,SI_MODE) VALUES (53007,'0','DELIVER IN PERSON','AIR');
INSERT INTO "DIMENSIONS"."SHIPMENT_INFO" (SI_SHIPMENTKEY,SI_PRIORITY,SI_INSTRUCTIONS,SI_MODE) VALUES (53008,'0','DELIVER IN PERSON','FOB');
INSERT INTO "DIMENSIONS"."SHIPMENT_INFO" (SI_SHIPMENTKEY,SI_PRIORITY,SI_INSTRUCTIONS,SI_MODE) VALUES (53009,'ShipPriority','ShipInstructions','ShipMode');
