#!/bin/bash

source /etc/rtwsrc

EC2_ZONES_TEMPLATE=/etc/bind/named.conf.options.template
EC2_ZONES_CONF=/etc/bind/named.conf.options

if [ "$reason" == BOUND ] || [ "$reason" == RENEW ] || [ "$reason" == REBIND ] || [ "$reason" == REBOOT ]; then

    if [ -n "$new_domain_name_servers" ]; then
    
        # Comment out the forwarding statement if we are running in the euca tms master instance
        if [ "$RTWS_IS_TMS" == "true" ] &&
           [[ "$RTWS_MANIFEST" == *master.ini ]] &&
           [[ "$RTWS_STORAGE_ENDPOINT" != *amazonaws* ]]; then
   
          cp $EC2_ZONES_TEMPLATE $EC2_ZONES_CONF
   
          if [ -e $EC2_ZONES_CONF ]; then
            sed -i "s|forwarders { __EC2_DNS_SERVERS__ };|// forwarders { __EC2_DNS_SERVERS__ };|" $EC2_ZONES_CONF
            sed -i "s|forward only;|// forward only;|" $EC2_ZONES_CONF
          fi
        else
          bind_forwarders=""
          for address in $new_domain_name_servers; do
            if [ "$address" != "127.0.0.1" ]; then 
              bind_forwarders="$bind_forwarders $address;"
            fi
          done
          
          sed "s/__EC2_DNS_SERVERS__/$bind_forwarders/" "$EC2_ZONES_TEMPLATE" > "$EC2_ZONES_CONF"
        fi
        
        /etc/init.d/bind9 reload
    fi

fi
