CREATE TABLE IF NOT EXISTS "APPLICATION"."NAMED_FILTER"
(
   KEY decimal(65535,32767) PRIMARY KEY NOT NULL,
   NAME varchar(25) NOT NULL,
   MODEL varchar(100) NOT NULL,
   DEFINITION varchar(4000) NOT NULL,
   EMAIL_SUBJECT varchar(100),
   EMAIL_MESSAGE varchar(4000)
);
CREATE UNIQUE INDEX PRIMARY_KEY_4 ON "APPLICATION"."NAMED_FILTER"(KEY);
CREATE UNIQUE INDEX NAMED_FILTER_UNIQUE ON "APPLICATION"."NAMED_FILTER"
(
  NAME,
  MODEL
);
CREATE TABLE IF NOT EXISTS "APPLICATION"."NAMED_FILTER_USERS"
(
   KEY decimal(65535,32767) PRIMARY KEY NOT NULL,
   USERNAME varchar(25) NOT NULL,
   PASSWORD varchar(125) NOT NULL,
   EMAIL_LIST varchar(4000)
);
CREATE UNIQUE INDEX PRIMARY_KEY_46 ON "APPLICATION"."NAMED_FILTER_USERS"(KEY);
CREATE UNIQUE INDEX NAMED_FILTER_USERS_UNIQUE ON "APPLICATION"."NAMED_FILTER_USERS"(USERNAME);
CREATE TABLE IF NOT EXISTS "APPLICATION"."NAMED_FILTER_WATCHLIST"
(
   USER_KEY decimal(65535,32767) NOT NULL,
   FILTER_KEY decimal(65535,32767) NOT NULL,
   COLOR decimal(65535,32767),
   EMAIL varchar(1),
   CONSTRAINT NAMED_FILTER_WATCHLIST_PK PRIMARY KEY (USER_KEY,FILTER_KEY)
);
CREATE UNIQUE INDEX PRIMARY_KEY_F ON "APPLICATION"."NAMED_FILTER_WATCHLIST"
(
  USER_KEY,
  FILTER_KEY
);

grant all on "COMMONDB"."APPLICATION"."NAMED_FILTER" to appuser
grant all on "COMMONDB"."APPLICATION"."NAMED_FILTER_USERS" to appuser
grant all on "COMMONDB"."APPLICATION"."NAMED_FILTER_WATCHLIST" to appuser