#!/bin/bash
set -e

source /etc/rtwsrc

# Apply Hive config
mkdir /etc/hive/conf/.bkup ; mv -f /etc/hive/conf/* /etc/hive/conf/.bkup
ln -sf ${deb.install.prefix}/cluster/* /etc/hive/conf/.
chown -h root:root /etc/hive/conf/*

# Copy the h2 libs under hive
cp /usr/local/rtws/commons-core/lib/h2* /usr/lib/hive/lib/. ; chown root:root /usr/lib/hive/lib/h2*.jar ; chmod 644 /usr/lib/hive/lib/h2*.jar 

# Update the expected port if needed based on datasink config
CONFIG_PREFIX="$(echo $RTWS_INGEST_CONFIG | sed "s/\.xml//g" | sed "s/services.//g" )"

if [ ! -z "CONFIG_PREFIX" ]; then

   RTWS_INGEST_CONFIG_DEFAULT="/usr/local/rtws/ingest/conf/pipeline.$CONFIG_PREFIX.default.xml"

   if [ -f $RTWS_INGEST_CONFIG_DEFAULT ]; then
	
		export EXPECTED_URL="$(cat $RTWS_INGEST_CONFIG_DEFAULT | awk -F'<metastore-url>' '{print $2}' | awk -F'</metastore-url>' '{print $1}' | tr -sd '\n' '')"
		export EXPECTED_IP="$(cat $RTWS_INGEST_CONFIG_DEFAULT | awk -F'<metastore-url>' '{print $2}' | awk -F'</metastore-url>' '{print $1}' | tr -sd '\n' '' | cut -d':' -f1-4 | cut -d'/' -f3)"
		EXPECTED_DRIVER_NAME="$(cat $RTWS_INGEST_CONFIG_DEFAULT | awk -F'<jdbc-driver-name>' '{print $2}' | awk -F'</jdbc-driver-name>' '{print $1}' | tr -sd '\n' '')"
		EXPECTED_USERNAME="$(cat $RTWS_INGEST_CONFIG_DEFAULT | awk -F'<username>' '{print $2}' | awk -F'</username>' '{print $1}' | tr -sd '\n' '')"
		EXPECTED_PASSWORD="$(cat $RTWS_INGEST_CONFIG_DEFAULT | awk -F'<password>' '{print $2}' | awk -F'</password>' '{print $1}' | tr -sd '\n' '')"

		if [ ! -z $EXPECTED_URL ]; then		
			echo "Updating the hive-server's url to ($EXPECTED_URL) for external connectivity."
			perl -i -pe 's:jdbc\:h2\:tcp\:\/\/hive-metastore\.RTWS_DOMAIN\:8161\/commondb\;SCHEMA_SEARCH_PATH\=METASTORE:$ENV{EXPECTED_URL}:g' /etc/hive/conf/hive-site.xml
			perl -i -pe 's:hive-metastore\.RTWS_DOMAIN\:9083:$ENV{EXPECTED_IP}\:9083:g' /etc/hive/conf/hive-site.xml
		fi
		
		if [ ! -z $EXPECTED_DRIVER_NAME ]; then		
			echo "Updating the jdbc driver to ($EXPECTED_DRIVER_NAME) for external connectivity."
			perl -i -pe "s/org\.h2\.Driver/$EXPECTED_DRIVER_NAME/g" /etc/hive/conf/hive-site.xml
		fi
		
		if [ ! -z $EXPECTED_USERNAME ]; then		
			echo "Updating the username to ($EXPECTED_USERNAME) for external connectivity."
			perl -i -pe "s/hiveuser/$EXPECTED_USERNAME/g" /etc/hive/conf/hive-site.xml
		fi
		
		if [ ! -z $EXPECTED_PASSWORD ]; then		
			echo "Updating the username to ($EXPECTED_PASSWORD) for external connectivity."
			perl -i -pe "s/\<value\>password\<\/value\>/\<value\>$EXPECTED_PASSWORD\<\/value\>/g" /etc/hive/conf/hive-site.xml
		fi
	fi
fi

# Replace the domain
perl -i -pe "s/RTWS_DOMAIN/$RTWS_DOMAIN/g" /etc/hive/conf/hive-site.xml
perl -i -pe "s/RTWS_ZOOKEEPER_QUORUM_SERVERS/$RTWS_ZOOKEEPER_QUORUM_SERVERS/g" /etc/hive/conf/hive-site.xml


# The current version of hue does not support ${var}  (which reads/depends on these configs from the hive metastore instance)
# used in hadoop configs so replace it with those variables
#
# TODO loop through all variables in /etc/rtwsrc, and replace as necessary
export R_DOMAIN=$RTWS_DOMAIN  # workaround for buggy env function below ???
perl -i -pe 's:\$\{RTWS_DOMAIN\}:$ENV{R_DOMAIN}:g' /etc/hadoop/conf/core-site.xml
perl -i -pe 's:\$\{RTWS_DOMAIN\}:$ENV{R_DOMAIN}:g' /etc/hadoop/conf/hdfs-site.xml
perl -i -pe 's:\$\{RTWS_DOMAIN\}:$ENV{R_DOMAIN}:g' /etc/hadoop/conf/mapred-site.xml

mkdir -p /tmp/hive/aux
cp -f ${deb.install.prefix}/hive-serde-1.0.jar /tmp/hive/aux/.
cp -f ${deb.install.prefix}/csv-serde-0.9.1.jar /tmp/hive/aux/.
chown -R hive:hive /tmp/hive