#!/bin/bash
set -e

source /etc/rtwsrc

# copy over the configs and modify as needed
rm -rf /etc/hue/* 2> /dev/null
mkdir -p /etc/hue/ 2> /dev/null
cp -f ${deb.install.prefix}/server/* /etc/hue/.

perl -i -pe "s/RTWS_NAMENODE_FQDN/namenode.$RTWS_DOMAIN/g" /etc/hue/hue.ini
perl -i -pe "s/RTWS_JOBTRACKER_FQDN/jobtracker.$RTWS_DOMAIN/g" /etc/hue/hue.ini
perl -i -pe "s/RTWS_FQDN/$RTWS_FQDN/g" /etc/hue/hue.ini
perl -i -pe "s/RTWS_DOMAIN/$RTWS_DOMAIN/g" /etc/hue/hue.ini

# The current version of hue does not support ${var} used in hadoop configs 
# so replace it with those variables
#
# TODO loop through all variables in /etc/rtwsrc, and replace as necessary
export R_DOMAIN=$RTWS_DOMAIN  # workaround for buggy env function below ???
export R_ZKSERVERS=$RTWS_ZOOKEEPER_QUORUM_SERVERS
perl -i -pe 's:\$\{RTWS_DOMAIN\}:$ENV{R_DOMAIN}:g' /etc/hadoop/conf/core-site.xml
perl -i -pe 's:\$\{RTWS_DOMAIN\}:$ENV{R_DOMAIN}:g' /etc/hadoop/conf/hdfs-site.xml
perl -i -pe 's:\$\{RTWS_DOMAIN\}:$ENV{R_DOMAIN}:g' /etc/hadoop/conf/mapred-site.xml
perl -i -pe 's:\$\{RTWS_ZOOKEEPER_QUORUM_SERVERS\}:$ENV{R_ZKSERVERS}:g' /etc/hbase/conf/hbase-site.xml
perl -i -pe "s/RTWS_FQDN/$RTWS_FQDN/g" /etc/hue/hue.ini

# Softlink the db to /mnt/rdafs for ebs persistence 
if [ ! -d /mnt/rdafs/hue ]; then
     mkdir -p /mnt/rdafs/hue ; chown hue:hue /mnt/rdafs/hue
fi

if [ ! -f /mnt/rdafs/hue/desktop.db ]; then
	 mv /usr/share/hue/desktop/desktop.db /mnt/rdafs/hue/.
	 ln -sf /mnt/rdafs/hue/desktop.db /usr/share/hue/desktop/.	 
fi

# TODO Remove linking in the hue.ini when using the CDHX version with hue 2.5 or greater is baked into the image
if [ -f /usr/share/hue/desktop/conf/hue.ini ]; then
	rm -f /usr/share/hue/desktop/conf/*
	ln -sf /etc/hue/* /usr/share/hue/desktop/conf/.
fi


# Toggle set -e to allow for the grep 
if [ ! -z ${deb.install.prefix}/scripts/prune_hive_logs.sh ]; then
	set +e
	CT="$(grep -cw prune_hive_logs.sh /etc/crontab 2> /dev/null)"
	if [ $CT -eq 0 ]; then
		set -e
		echo -e "*/45 * * * * root ${deb.install.prefix}/scripts/prune_hive_logs.sh\n" >> /etc/crontab
	fi	
fi