#!/bin/bash
set -e

source /etc/rtwsrc

# Set the memory size to specific values (can't assume % of available due to other components on the same node)
AVAILABLE_MEMORY_IN_MB="$(free -m | grep Mem | awk '{print $2}')"
export RTWS_IMPALA_HEAPSIZE=1024m

if [ -z $AVAILABLE_MEMORY_IN_MB ]; then
        echo "Unable to determine the amount of available memory, using defaults." | logger
else
        # If less than or equal 8 GB, only allocate 1 GB
        if [ $AVAILABLE_MEMORY_IN_MB -le 8096 ]; then
            export RTWS_IMPALA_HEAPSIZE=1024m
                   
        # If less than or equal 12 GB, allocate 8 GB
        elif [ $AVAILABLE_MEMORY_IN_MB -le 12288 ]; then
            export RTWS_IMPALA_HEAPSIZE=8192m
            
        # If more than 32 GB, only allocate 16 GB
        elif [ $AVAILABLE_MEMORY_IN_MB -ge 32768 ]; then                
            export RTWS_IMPALA_HEAPSIZE=16384m
        fi
fi

cp -f ${deb.install.prefix}/default/impala /etc/default/. 
perl -i -pe "s/JOBTRACKER_FQDN/jobtracker.$RTWS_DOMAIN/g" /etc/default/impala
perl -i -pe "s/RTWS_IMPALA_HEAPSIZE/$RTWS_IMPALA_HEAPSIZE/g"  /etc/default/impala
chmod 444 /etc/default/impala

# Copy over the required configs
cp -f /etc/hadoop/conf/core-site.xml /etc/impala/conf/.
cp -f /etc/hadoop/conf/hdfs-site.xml /etc/impala/conf/.
cp -f /etc/hive/conf/hive-site.xml /etc/impala/conf/.
cp -f ${deb.install.prefix}/default/impala /etc/default/.
cp -f ${deb.install.prefix}/default/impala-catalog /etc/init.d/.
cp -f ${deb.install.prefix}/default/impala-server /etc/init.d/.
cp -f /etc/zookeeper/conf/zoo.cfg /etc/impala/conf/.
perl -i -pe "s/RTWS_DOMAIN/$RTWS_DOMAIN/g" /etc/impala/conf/hive-site.xml


# Impala doesn't handle property replacement so update the configs
export R_DOMAIN=$RTWS_DOMAIN  # workaround for buggy env function below ???
export R_ZOOKEEPER_QUORUM_SERVERS=$RTWS_ZOOKEEPER_QUORUM_SERVERS
perl -i -pe 's:\$\{RTWS_DOMAIN\}:$ENV{R_DOMAIN}:g' /etc/impala/conf/core-site.xml
perl -i -pe 's:\$\{RTWS_DOMAIN\}:$ENV{R_DOMAIN}:g' /etc/impala/conf/hdfs-site.xml