---
# This playbook configures a Hadoop cluster as managed by DE configuration  

# Assumes running local "aka -c local"
- hosts: all
  vars:
     RTWS_DOMAIN: "{{ lookup('pipe', 'grep RTWS_DOMAIN /etc/rtwsrc | cut -d= -f2') }}"
     RTWS_ZOOKEEPER_QUORUM_SERVERS: "{{ lookup('pipe', 'grep RTWS_ZOOKEEPER_QUORUM_SERVERS /etc/rtwsrc | cut -d= -f2') }}"
     deb_install_prefix: /usr/local/hadoop-config
    
  roles:
  - common