create unique index	CUSTOMER_NK		ON DIMENSIONS.CUSTOMER(C_NAME);
create index		DATE_DIM_FULL_DATE	ON DIMENSIONS.DATE_DIM(FULL_DATE);
create unique index	EVENT_TYPE_NK		ON DIMENSIONS.EVENT_TYPE(EVENT_TYPE);
create unique index	NAMED_FILTER_UNIQUE	ON APPLICATION.NAMED_FILTER(NAME, MODEL);
create unique index	NAMED_FILTER_USERS_UNIQUE ON APPLICATION.NAMED_FILTER_USERS(USERNAME);
create unique index	NATION_PK		ON DIMENSIONS.NATION(N_NATIONKEY);
create unique index	OBJECT_NK		ON DIMENSIONS.OBJECT(OBJECT_TYPE, OBJECT_ID_NAME, OBJECT_ID_VALUE);
create unique index	PART_NK			ON DIMENSIONS.PART(P_NAME);
create unique index	REGION_NK		ON DIMENSIONS.REGION(R_NAME);
create unique index	SUPPLIER_NK		ON DIMENSIONS.SUPPLIER(S_NAME);
create index		ZION_NATKEY_INDEX	ON DIMENSIONS.ZIONTRACKING(BANK, ACCOUNT, TRANSACTIONTYPE, DATESTAMP);

