GRANT ALL ON APPLICATION.ALERTVIZ_GRAPHSETTINGS TO APPUSER;
GRANT ALL ON APPLICATION.NAMED_FILTER TO APPUSER;
GRANT ALL ON APPLICATION.NAMED_FILTER_USERS TO APPUSER;
GRANT ALL ON APPLICATION.NAMED_FILTER_WATCHLIST TO APPUSER;
GRANT ALL ON APPLICATION.NEW_TABLE TO APPUSER;
GRANT ALL ON APPLICATION.SCHEDULED_TASKS TO APPUSER;
GRANT ALL ON APPLICATION.IAAS_ACCOUNT_SYSTEM_USAGE TO APPUSER;
GRANT ALL ON APPLICATION.IAAS_ACCOUNT_SYSTEM_USAGE_SUMMARY TO APPUSER;